const CartActionTypes = {
  TOGGLE_CART_MENU: "TOGGLE_CART_MENU",
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  REMOVE_WHOLE_ITEM_FROM_CART: "REMOVE_WHOLE_ITEM_FROM_CART",
  REMOVE_SINGLE_ITEM_FROM_CART: "REMOVE_SINGLE_ITEM_FROM_CART",
};

export default CartActionTypes;
